name: Telegram Reminder

on:
  push:
    branches:
      - main  # سيعمل عند أي تعديل يتم دفعه لفرع main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🔔 تم تحديث المستودع بنجاح!"
